version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: db_futgol
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19thi19
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      POSTGRES_DB: db_futgol
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19thi19
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5432
      CORS_ALLOWED_ORIGIN: http://localhost:3000
      DJANGO_SECRET_KEY: dev-secret-key
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
volumes:
  pgdata:
